services:
  db:
    image: postgres:16
    container_name: reqtracker_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Holapapus
      POSTGRES_DB: reqtracker
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
